name: Build and Publish Docker

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build \
            --build-arg BUILD_NUMBER=${{ github.run_number }} \
            -t ghcr.io/${{ github.repository }}:latest .
      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
